services:
  app:
    build: .
    # command: python main.py
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    volumes:
      - .:/app

  postgres_db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hw_06_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:


# version: '3.8'

# services:
#   postgres_db:
#     image: postgres:14-alpine
#     restart: always
#     environment:
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: admin
#       POSTGRES_DB: hw_06_db
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/

#   app:
#     build: .
#     restart: on-failure
#     depends_on:
#       - postgres_db
#     environment:
#       DATABASE_URL: postgresql+asyncpg://postgres:565656@postgres_db:5432/postgres
#     volumes:
#       - .:/app
#     # Ця команда тримає контейнер живим, не виконуючи нічого.
#     command: tail -f /dev/null

# volumes:
#   postgres_data:
