[project]
name = "goit-pythonweb-hw-06"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.16.5",
    "asyncpg>=0.30.0",
    "faker>=37.6.0",
    "sqlalchemy>=2.0.43",
    "black==25.1.0",
]
