"""Add student_last_name to students table

Revision ID: 0322e095e0ef
Revises: d49523dc7840
Create Date: 2025-09-01 20:12:36.864710

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0322e095e0ef"
down_revision: Union[str, Sequence[str], None] = "d49523dc7840"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "students", sa.Column("student_last_name", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("students", "student_last_name")
    # ### end Alembic commands ###
